version: 2
jobs:
  build:
    macos:
      xcode: "9.0"

    steps:
      - checkout

      - run:
          name: Install required software
          command: |
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable

      - run:
          name: Unit tests
          command: |
                export PATH=$PATH:$HOME/.cargo/bin
                cargo test

      - run:
          name: Build
          command: |
              export PATH=$PATH:$HOME/.cargo/bin:$PWD/janusbin
              cargo build --all --verbose --release
